#!/usr/bin/env python3
"""Generate docs/assets/css/tokens.css from replica/design/tokens.json.

The JSON is the source of truth (replica-design). Components in site.css
only ever use the custom properties this writes, never raw values.

    python3 tools/build_tokens.py           # write the CSS
    python3 tools/build_tokens.py --check   # exit 1 if the CSS is stale

Standard library only.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "replica" / "design" / "tokens.json"
OUT = ROOT / "docs" / "assets" / "css" / "tokens.css"


def px(value):
    return "0" if value == 0 else "%gpx" % value


def render(tokens):
    lines = [
        "/* Generated by tools/build_tokens.py from replica/design/tokens.json.",
        "   Do not edit by hand: change the JSON and re-run the script. */",
        ":root {",
    ]
    for name, value in tokens["color"].items():
        lines.append("  --c-%s: %s;" % (name, value))
    for name, value in tokens["font"].items():
        lines.append("  --font-%s: %s;" % (name, value))
    for name, spec in tokens["type"].items():
        lines.append("  --fs-%s: %s;" % (name, px(spec["size"])))
        lines.append("  --lh-%s: %s;" % (name, px(spec["line"])))
        lines.append("  --fw-%s: %s;" % (name, spec["weight"]))
    for i, value in enumerate(tokens["space"]):
        lines.append("  --space-%d: %s;" % (i, px(value)))
    for name, value in tokens["radius"].items():
        lines.append("  --radius-%s: %s;" % (name, px(value)))
    for name, value in tokens["shadow"].items():
        lines.append("  --shadow-%s: %s;" % (name, value))
    for name, value in tokens["motion"].items():
        lines.append("  --motion-%s: %s;" % (name, value))
    layout = tokens["layout"]
    for name in ("max", "gutter", "gutter-mobile", "header"):
        lines.append("  --layout-%s: %s;" % (name, px(layout[name])))
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    css = render(json.loads(SRC.read_text(encoding="utf-8")))
    if "--check" in sys.argv[1:]:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != css:
            print("tokens.css is out of date: run python3 tools/build_tokens.py")
            return 1
        print("tokens.css is up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(css, encoding="utf-8")
    print("wrote %s" % OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
